smtp.host=smtp.gmail.com
smtp.port=587
smtp.sender.id=khorospv@gmail.com
smtp.sender.password=fkcsxxlunfwucmho
server.port=8090
notification.email.targets=anandbolli@gmail.com,candy.shakthi@gmail.com,sivasakthi.baskaran@sutherlandglobal.com,Anand.Bolli1@sutherlandglobal.com
